project_name: languagetool-code-comments
builds:
  - main: ./tools/goreleaser.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    hooks:
      post: ./tools/goreleaser-dist.sh {{ .Target }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format_overrides:
    - goos: windows
      format: zip
    files:
      - completions/*
      - LICENSE
      - THIRDPARTY.html

signs:
  - artifacts: checksum
    args: ["-u", "6A34CFEE77FE8257C3BB92FE24C3FC5D6987904B", "--output", "${signature}", "--detach-sign", "${artifact}"]

brews:
  - tap:
      owner: dustinblackman
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/dustinblackman/languagetool-code-comments
    description: Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!
    test: |
      system "#{bin}/languagetool-code-comments --version"
    install: |
      # Install languagetool-code-comments
      bin.install "languagetool-code-comments"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "bash")
      (bash_completion/"languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "zsh")
      (zsh_completion/"_languagetool-code-comments").write output

      output = Utils.safe_popen_read("#{bin}/languagetool-code-comments", "completion", "-s", "fish")
      (fish_completion/"languagetool-code-comments.fish").write output

scoop:
  bucket:
    owner: dustinblackman
    name: scoop-bucket
  homepage: https://github.com/dustinblackman/languagetool-code-comments
  description: Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!
  license: MIT

nfpms:
  - homepage: https://github.com/dustinblackman/languagetool-code-comments
    description: Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!
    maintainer: Dustin Blackman
    vendor: Dustin Blackman
    formats:
      - deb
      - rpm
    contents:
      - src: ./completions/languagetool-code-comments.bash
        dst: /usr/share/bash-completion/completions/languagetool-code-comments
        file_info:
          mode: 0644
      - src: ./completions/languagetool-code-comments.fish
        dst: /usr/share/fish/completions/languagetool-code-comments.fish
        file_info:
          mode: 0644
      - src: ./completions/languagetool-code-comments.zsh
        dst:  /usr/share/zsh/vendor-completions/_languagetool-code-comments
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/languagetool-code-comments/copyright/LICENSE
        file_info:
          mode: 0644
      - src: ./THIRDPARTY.html
        dst: /usr/share/doc/languagetool-code-comments/copyright/THIRDPARTY.html
        file_info:
          mode: 0644

aurs:
  - name: languagetool-code-comments-bin
    homepage: https://github.com/dustinblackman/languagetool-code-comments
    description: Integrates the LanguageTool API to parse, spell check, and correct the grammar of your code comments!
    maintainers:
      - "Dustin Blackman"
    contributors:
      - "Dustin Blackman"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/languagetool-code-comments-bin.git"
    package: |-
        # bin
        install -Dm755 "./languagetool-code-comments" "${pkgdir}/usr/bin/languagetool-code-comments"

        # license
        install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/languagetool-code-comments/LICENSE"
        install -Dm644 "./THIRDPARTY.html" "${pkgdir}/usr/share/licenses/languagetool-code-comments/THIRDPARTY.html"

        # completions
        mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
        mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
        mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
        install -Dm644 "./completions/languagetool-code-comments.bash" "${pkgdir}/usr/share/bash-completion/completions/languagetool-code-comments"
        install -Dm644 "./completions/languagetool-code-comments.zsh" "${pkgdir}/usr/share/zsh/site-functions/_languagetool-code-comments"
        install -Dm644 "./completions/languagetool-code-comments.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/languagetool-code-comments.fish"

changelog:
  use: github-native
