[alias]
about = ["bin", "cargo-about"]
binstall = ["bin", "cargo-binstall"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
gha = ["bin", "cargo-gha"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
xwin = ["bin", "cargo-xwin"]
zigbuild = ["bin", "cargo-zigbuild"]
