[alias]
binstall = ["bin", "cargo-binstall"]
bundle-licenses = ["bin", "cargo-bundle-licenses"]
cmd = ["bin", "cargo-cmd"]
deny = ["bin", "cargo-deny"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
