on: workflow_dispatch
name: build
jobs:
  linux-amd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Build
        run: |
          git submodule update --init --recursive
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          path: target/x86_64-unknown-linux-gnu/release/languagetool-code-comments

  linux-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - name: Build
        run: |
          git submodule update --init --recursive
          sudo apt-get install gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          cargo install cargo-zigbuild --version 0.18.0
          cargo zigbuild --release --target aarch64-unknown-linux-gnu
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release/languagetool-code-comments

  macos-amd:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-apple-darwin
          toolchain: stable
      - name: Build
        run: |
          git submodule update --init --recursive
          cargo build --release --target x86_64-apple-darwin
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-apple-darwin
          path: target/x86_64-apple-darwin/release/languagetool-code-comments

  macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: aarch64-apple-darwin
      - name: Build
        run: |
          git submodule update --init --recursive
          cargo install cargo-zigbuild --version 0.18.0
          rustup target add aarch64-apple-darwin
          cargo zigbuild --release --target aarch64-apple-darwin
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: aarch64-apple-darwin
          path: target/aarch64-apple-darwin/release/languagetool-code-comments

  windows-amd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-pc-windows-msvc
      - name: Build
        run: |
          git submodule update --init --recursive
          rustup target add x86_64-pc-windows-msvc
          cargo install cargo-xwin --version 0.16.0
          cargo xwin build --release --target x86_64-pc-windows-msvc --xwin-arch x86_64
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-pc-windows-msvc
          path: target/x86_64-pc-windows-msvc/release/languagetool-code-comments.exe
